---
- name: Run miniconda role
  include_role:
    name: uchida.miniconda
    public: true
  vars:
    miniconda_prefix: '{{ conda_prefix }}'
    miniconda_version: '{{ conda_version }}'

- name: Configure bashrc
  blockinfile:
    path: '/root/.bashrc'
    insertafter: EOF
    block: |
      # >>> conda initialize >>>
      # !! Contents within this block are managed by 'conda init' !!
      __conda_setup="$('{{ conda_prefix }}/bin/conda' 'shell.bash' 'hook' 2> /dev/null)"
      if [ $? -eq 0 ]; then
          eval "$__conda_setup"
      else
          if [ -f "{{ conda_prefix }}/etc/profile.d/conda.sh" ]; then
              . "{{ conda_prefix }}/etc/profile.d/conda.sh"
          else
              export PATH="{{ conda_prefix }}/bin:$PATH"
          fi
      fi
      unset __conda_setup
      # <<< conda initialize <<<
