---
# tasks file for ansible-role-laniakea-utils

- name: Include Docker role
  include_role:
    name: indigo-dc.docker
    public: true
  when: install_docker

- name: Include miniconda role
  include_role:
    name: uchida.miniconda
  when: install_conda
