---
# tasks file for ansible-role-laniakea-utils

- name: Create laniakea user
  user:
    name: 'laniakea'
    shell: '/bin/bash'
    create_home: no

- name: Enable laniakea user to run laniakea-utils
  lineinfile:
    dest: '/etc/sudoers'
    line: 'laniakea ALL=NOPASSWD:{{ nginx_restart_command }},{{ galaxy_restart_command }}'
    state: present
    insertafter: EOF

- name: '[EL] Install prerequisites'
  package:
    name:
      - python3
      - python3-pip
      - python3-virtualenv
    state: present

- debug:
    msg: '{{ venv }}'

- name: Verify if laniakea-utils is installed
  stat:
    path: '{{ venv }}'
  register: is_installed

- debug:
    msg: '{{ is_installed.stat }}'

- block:

  - name: Create venv
    pip:
      name: pip
      virtualenv: '{{ venv }}'
      virtualenv_command: python3 -m virtualenv

  - name: Install laniakea-utils
    pip:
      name: 'laniakea-utils'
      version: '{{ version }}'
      virtualenv: '{{ venv }}'
    become_user: root
    become_method: sudo

  when: not is_installed.stat.exists

- name: Create laniakea-utils config dir
  file:
    path: /etc/laniakea
    state: directory

- name: Configure Laniakea-utils
  template:
    src: laniakea-utils.ini.j2
    dest: /etc/laniakea/laniakea-utils.ini

- name: Install systemd unit file
  template:
    src: laniakea-utils.service.j2
    dest: /etc/systemd/system/laniakea-utils.service

- name: Start and enable laniakea-utils
  service:
    name: laniakea-utils
    state: restarted
    enabled: yes
