---
# tasks file for ansible-role-laniakea-utils

- name: Include Docker role
  include_role:
    name: indigo-dc.docker
  vars:
    docker_config:  { "data-root": "{{ export_dir }}/docker_image", }
  when: install_docker

- name: Include miniconda role
  include_role:
    name: uchida.miniconda
  vars:
    miniconda_prefix: "{{ miniconda_prefix }}"
    miniconda_version: "4.6.14"
  when: install_conda
